name: Publish release

on:
  push:
    tags: [ "v*" ]

permissions:
  contents: read

jobs:
  pypi:
    uses: MartinPdeS/MPSActions/.github/workflows/publish_pure_package_to_PyPi.yml@v5
    with:
      python-version: "3.11"
      test-command: "python -c 'import DeepPeak; print(DeepPeak.__version__)'"
    secrets:
      PYPI_API_TOKEN: ${{ secrets.PYPI_API_TOKEN }}

  conda:
    uses: MartinPdeS/MPSActions/.github/workflows/publish_compiled_package_to_anaconda.yml@v3
    with:
      python_versions: '["3.11"]'
      os_list: '["ubuntu-latest"]'
      package_name: deeppeak
      recipe_path: conda.recipe
      test_import: DeepPeak
    secrets:
      ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_API_TOKEN }}
