name: Deploy coverage

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: write

jobs:
  ManyLinux_x86_64:
    uses: MartinPdeS/MPSActions/.github/workflows/publish_coverage.yml@v5
    with:
      python-version: "3.11"
      coverage-package: DeepPeak
    secrets:
      _GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
